### ISSUE TITLE
[discussion] Default root size - 20GB

### ISSUE THREAD

**Issue by ozbillwang** [awslabs/amazon-eks-ami#13]
I run EKS cluster for one week, already get "no space" issue on EKS workers.

Found the code here that the default root size is 20GB.

https://github.com/awslabs/amazon-eks-ami/blob/master/eks-worker-al2.json#L22

          "volume_size": 20,

Should we increase it to 50GB or more? 

I can update my codes to start with more space, but 20GB is too small, which I recommend to update in this AMI directly.

**Comment by micahhausler** [comment]
This can be overridden when you launch a node group by editing the CloudFormation template, 

```yaml
  NodeLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ...
      BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          DeleteOnTermination: true
          VolumeType: gp2
          VolumeSize: 50
```
