### ISSUE TITLE
Increase in memory usage after switching to AMI release v20230526

### ISSUE THREAD

**Issue by joseguerrero** [awslabs/amazon-eks-ami#1352]
**What happened**:

Recently I upgraded EKS clusters to version `1.23`. In version `1.22` I was using the AMI release `v20230217` and for `1.23` I selected `v20230526`, which was the latest version with no issues reported by the time.

Right after upgrading, I noticed that some applications started to show an unusual memory usage increase over time. So far I have identified this behavior in two different applications, Envoy proxy and the `clouddriver` component of Spinnaker. Here I attach some dashboards representative of the timeline when the upgrade took place and how the memory usage increased.

![Screenshot from 2023-07-13 13-29-26](https://github.com/awslabs/amazon-eks-ami/assets/3450341/cd0d4ed8-cb3e-451e-a376-84d1ed5c9766)

I suspect that the behavior change might be related to the change of the kernel version, from `5.4.228-132.418` to `5.4.242-155.348`.

**What you expected to happen**:

I would expect the memory usage to remain the same as with the previous AMI release `v20230217`.

**How to reproduce it (as minimally and precisely as possible)**:

In an EKS cluster `v1.23`, with two self-managed node groups:

- One using AMI release `v20230526`
- One using AMI release `v20230217`

Deploy a bare Envoy proxy pod using the following image and tag `envoyproxy/envoy:v1.21.2` on each node group. No need to route any traffic to the pods.

After some hours, it should be evident that Envoy's memory usage in the `v20230526` node group is higher and grows at a faster rate compared to the `v20230217` node group. See the following captures for a reference comparison:

In node group using AMI release `v20230217` with kernel version `5.4.228-132.418`

![image](https://github.com/awslabs/amazon-eks-ami/assets/3450341/c82d2021-f00e-4b95-8aa3-4dcb9d91a666)

In node group using AMI release `v20230526` with kernel version `5.4.242-155.348`

![image](https://github.com/awslabs/amazon-eks-ami/assets/3450341/069ca1b4-da46-4e07-b18f-e747d28b09bb)

**Anything else we need to know?**:

**Environment**:
- AWS Region: eu-west-1
- Instance Type(s): m6a.12xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): "eks.10"
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):"1.23"
- AMI Version: `v20230526`
- Kernel (e.g. `uname -a`): 5.4.242-155.348.amzn2.x86_64
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-03a6fab5b8d8bfd7b"
BUILD_TIME="Fri May 26 16:07:12 UTC 2023"
BUILD_KERNEL="5.4.242-155.348.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by cartermckinnon** [comment]
Are you able to reproduce this on the latest AMI release? I want to make sure it's an active issue before we go down any rabbit holes. 😄

**Comment by joseguerrero** [comment]
Hi @cartermckinnon, thank you for following up. Yes, I was able to reproduce it also with `v20230703`
![Screenshot from 2023-07-15 15-39-06](https://github.com/awslabs/amazon-eks-ami/assets/3450341/5554dd5d-6a41-46b1-a634-89fc7079b564)

**Comment by cartermckinnon** [comment]
Hm okay. I'm curious if we can reproduce this outside a container. This is also a fairly old version of Envoy; do you see the same behavior on current versions?

**Comment by joseguerrero** [comment]
> do you see the same behavior on current versions?

Yes, it is slightly better with Envoy `v1.26.2` but it still shows the same trend. I have the same setup running in multiple node groups for comparison:

Envoy `1.26.2` with kernel `5.4.228-132.418.amzn2.x86_64`

![image](https://github.com/awslabs/amazon-eks-ami/assets/3450341/64a912b3-3ecb-43b1-ad45-36275b5fa9de)

Envoy `1.26.2` with kernel `5.4.242-155.348.amzn2.x86_64`

![image](https://github.com/awslabs/amazon-eks-ami/assets/3450341/80142888-cc5e-48c1-94ca-662875102920)

**Comment by cartermckinnon** [comment]
Thanks!

It's suspicious to me that the metric is exactly 2x. What are you using to scrape these?

**Comment by joseguerrero** [comment]
> What are you using to scrape these?

Standard prometheus operator setup, the exact query for the dashboard is: 

```
sum(container_memory_working_set_bytes{namespace="$namespace", pod="$pod", container="$container", container!="POD", container!="", image!=""}) by (container)
```

**Comment by joseguerrero** [comment]
To try to confirm/discard that this could be caused by duplicated metrics, I checked the memory usage directly from within the pod:

with `top` from the Envoy `1.26.2` pod with `5.4.242-155.348.amzn2.x86_64`

![image](https://github.com/awslabs/amazon-eks-ami/assets/3450341/2ca515a4-42d1-4dd1-8593-28d2e83179a1)

with `top` from the Envoy `1.26.2` pod with `5.4.228-132.418.amzn2.x86_64`

![image](https://github.com/awslabs/amazon-eks-ami/assets/3450341/c9aa4469-b81c-4b3c-95d8-1f579a667cea)

**Comment by cartermckinnon** [comment]
I'll try to repro. I've deployed an env and will check back tomorrow morning.

Cluster:
```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: "envoy-mem-usage"
  region: us-west-2
  version: "1.27"
managedNodeGroups:
  - name: 127-20230711
    ami: ami-03e2c58d85e0721a5
    amiFamily: AmazonLinux2
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    overrideBootstrapCommand: |
      #!/bin/bash
      source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh      
      /etc/eks/bootstrap.sh envoy-mem-usage --kubelet-extra-args "--node-labels=${NODE_LABELS}"
  - name: 123-20230711
    ami: ami-0ccc6f85fc153843c
    amiFamily: AmazonLinux2
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    overrideBootstrapCommand: |
      #!/bin/bash
      source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh      
      /etc/eks/bootstrap.sh envoy-mem-usage --kubelet-extra-args "--node-labels=${NODE_LABELS}"
  - name: 123-20230217
    ami: ami-07bbd06190de13379
    amiFamily: AmazonLinux2
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    overrideBootstrapCommand: |
      #!/bin/bash
      source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh      
      /etc/eks/bootstrap.sh envoy-mem-usage --kubelet-extra-args "--node-labels=${NODE_LABELS}"
```

envoy:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: envoy
spec:
  selector:
    matchLabels:
      name: envoy
  template:
    metadata:
      labels:
        name: envoy
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.26.2
```

Installed metrics-server:
```
kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
```

After ~15 minutes, mem usage is identical for all the nodes and isn't increasing, as told by `kubectl top pod` and `systemd-cgtop -p` on each node.

**Comment by cartermckinnon** [comment]
I see no increase in memory usage after 19 hours, and the usage is the same across the 3 AMI's in my environment. @joseguerrero let me know if you have a different repro working.

**Comment by joseguerrero** [comment]
Hi @cartermckinnon, thank you for sharing the details about your test setup, I'll try to do something similar on my side this week and see if I can reproduce the problem and then share an update here.

**Comment by cartermckinnon** [comment]
Sounds good! After ~5 days, I see no increase in memory usage, or any difference across the AMI's in my environment.

**Comment by parkergordonio** [comment]
@joseguerrero Any findings? We experienced the same memory increase for our Envoy service mesh containers EKS back in April 2023 when we attempted to upgrade our AMI version. We ultimately postponed the upgrade until now. Seeing roughly 40-70% more memory consumption for all envoy instances.

**Comment by joseguerrero** [comment]
Hi! Sorry, last week was quite busy. Yes I have some findings.

First I tried to reproduce the issue with a setup similar to what @cartermckinnon described, and indeed I didn't see any memory increase over time, so then I tried to find what could be different between that setup and what we use at my company. The one thing that I could confirm has an impact on the memory usage is having a service linked to the envoy workload, so using this minimal deployment setup I was still able to reproduce the memory increase issue:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-envoy-1-26
spec:
  selector:
    matchLabels:
      name: svc-envoy-1-26
  template:
    metadata:
      labels:
        name: svc-envoy-1-26
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.26.2
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: "0.2"
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /
            port: 10000
            scheme: HTTP
        ports:
        - containerPort: 10000
          name: http
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-envoy-1-26
  name: svc-envoy-1-26
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: svc-envoy-1-26
```

I still want to run some more comparisons between the different AMI versions, and share the results here, hopefully in the next few days.
