### ISSUE TITLE
[runc-1.1.7-3.amzn2] Cannot run executable found relative to current directory

### ISSUE THREAD

**Issue by jBouyoud** [awslabs/amazon-eks-ami#1410]
**What happened**:

When running a pod with a private image with a ruby/rails application we got the following error message on start :
```
Last State: Terminated
  Reason: StartError
  Message: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start 
      container process: exec: "rails": cannot run executable found relative to current directory: unknown
   Exit Code: 128
   Started: Thu, 01 Jan 1970 01:00:00 +0100
   Finished: Wed, 30 Aug 2023 16:55:15 +0200
```

We notice some strange things :
- `unknown` current working dir
- Started at epoch 0

Our image define a PATH environment variable to add a relative path like `ENV PATH=bin:$PATH` (and `WORKDIR` is also correctly set on out docker image).
Adding `.spec.workingDir` on pod definition doesn’t change the behavior.

**What you expected to happen**:

To run a pod normally without any error.
The same pod definition run perfectly on `v1.26.6-eks-a5565ad`. 

**How to reproduce it (as minimally and precisely as possible)**:

Run the same pod definition on `v1.26.7-eks-8ccc7ba  / ami-0c8f13e2e3c8de829` node.

**Anything else we need to know?**:

**Environment**:
- AWS Region: eu-west-3
- Instance Type(s): Spot - with karpenter with the following constraints : 
```
    requirements:
    - key: topology.kubernetes.io/zone
      operator: In
      values:
      - eu-west-3a
      - eu-west-3b
      - eu-west-3c
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn
      values:
      - nano
      - micro
      - small
      - medium
      - large
      - xlarge
      - metal
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values:
      - m
      - r
      - c
    - key: karpenter.sh/capacity-type
      operator: In
      values:
      - spot
      - on-demand
    - key: kubernetes.io/os
      operator: In
      values:
      - linux
```
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.5
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.26
- AMI Version: AMI Release v20230825
- Kernel (e.g. `uname -a`): 5.10.186-179.751.amzn2.x86_64
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-0f2b325398f933a81"
BUILD_TIME="Fri Aug 25 20:12:27 UTC 2023"
BUILD_KERNEL="5.10.186-179.751.amzn2.x86_64"
ARCH="x86_64"
```
