### ISSUE TITLE
File descriptor limit change in AMI release `v20231220`

### ISSUE THREAD

**Issue by mmerkes** [awslabs/amazon-eks-ami#1551]
**What happened**:
Customers are reporting hitting ulimits as a result of this PR #1535
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- AWS Region:
- Instance Type(s):
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version:
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by johnkeates** [comment]
We have hit this issue too, we have about ~1700 pods crashlooping in each cluster. I wonder if the CI doesn't test using a large enough workload?

**Comment by mmerkes** [comment]
We have already reverted the change that caused this issue (#1535), we're rolling back the `v20231220` release and we're preparing to release new AMIs without the change ASAP. More guidance to come.

**Comment by maksim-paskal** [comment]
It help us to restore our pods on new nodes, we using Karpenter

```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
...
spec:
 ....
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="BOUNDARY"

    --BOUNDARY
    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash

    rm -rf /etc/systemd/system/containerd.service.d/20-limitnofile.conf

    --BOUNDARY--
```
and drain all new nodes from cluster
