### ISSUE TITLE
[Feature] Publish binary w/ ability to validate the user supplied configuration

### ISSUE THREAD

**Issue by bryantbiggs** [awslabs/amazon-eks-ami#1785]
**What would you like to be added**:
- Two parts:
	1. Build and publish the `nodeadm` binary to allow users to download and use the executable in a CLI type fashion locally
	2. Add a command such as `--validate` that accepts a file path to a config to let users validate their configuration. If the config is valid, say it passed with a 0 exit code. If it fails, log out which field(s) that failed to match the schema and exit with non-zero. If there are additional fields, it would be nice to point those out as well so that folks do not assume they are actually doing something (I don't know if current schema validation logic is exhaustive or not, if it is - great)
	
- An added bonus that is sometimes helpful, if there was a command that dumped out the full, potential config with its types, something like shown below. This helps both new users understand what can be set and how, as well as those users who are using `--validate` that are struggling to configure settings (if they can see the schema, maybe that connects the dots for them or even tells them if its a setting they can configure)

Example:

```yaml
apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
  cluster:
    name: <String>
    apiServerEndpoint: <String>
    certificateAuthority: <String>
    cidr: <String>
    kubelet:
      config:
        shutdownGracePeriod: <String>
        featureGates:
          DisableKubeletCloudCredentialProviders: <Bool>
```

**Why is this needed**:

- Improve usability and allow users to better self-serve (troubleshoot on their own)
