### ISSUE TITLE
/etc/eks/bootstrap.sh devops3-vlocity-kube --kubelet-extra-args "--node-labels=jenkins=true --register-with-taints=dedicated=jenkins:NoSchedule"

### ISSUE THREAD

**Issue by Sam123ben** [awslabs/amazon-eks-ami#179]
**What happened**:
I dont see the taints happening but can find the labels got modified on the nodes whjich is good. But I dont see the nodes got tainted as I was expecting.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- AWS Region:
- Instance Type(s):
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version:
- Kernel (e.g. `uname -a`):
- Release information (run `cat /tmp/release` on a node):

```
```

**Comment by Sam123ben** [comment]
I used the below command with the double quotes and again tried with the single quotes as well.
/etc/eks/bootstrap.sh devops3-vlocity-kube --kubelet-extra-args "--node-labels=jenkins=true --register-with-taints=dedicated=jenkins:NoSchedule"

**Comment by gacopl** [comment]
Hello mate, it's because you are not escaping stuff properly. Such user-data works for me without problem

/etc/eks/bootstrap.sh plab --kubelet-extra-args "--node-labels=role=elastic-node --eviction-hard=\"memory.available<500Mi,nodefs.available<2Gi,nodefs.inodesFree<5%\" --register-with-taints=\"role=elastic-node:NoSchedule\" --system-reserved=memory=1Gi --kube-reserved=memory=100Mi"

**Comment by micahhausler** [comment]
As @gacopl noted, you need to properly escape quotes. Does that fix the issue for you?

**Comment by Bwvolleyball** [comment]
Does anyone happen to know how those escapes change if the script is being called via terraform?

Here's how we set up the call to the script in terraform:

The only part I'm unclear about is how to configure the `--kubelet-extra-args` portion.

```
locals {
  node-data = <<DATA
#!/bin/bash
set -o xtrace
/etc/eks/bootstrap.sh terraform-eks-zpeks
/opt/aws/bin/cfn-signal --exit-code $? \
	 --stack  terraform-eks-zpeks \
	 --resource NodeGroup  \
	 --region us-west-2  \
     --kubelet-extra-args  \
     "--register-with-taints="environment=dev:NoSchedule"  \
     --node-labels=com.zenplanner/environment=dev"
DATA
}
```

**Comment by Bwvolleyball** [comment]
Does anyone happen to know how those escapes change if the script is being called via terraform?

Here's how we set up the call to the script in terraform:

The only part I'm unclear about is how to configure the `--kubelet-extra-args` portion.

```
locals {
  node-data = <<DATA
#!/bin/bash
set -o xtrace
/etc/eks/bootstrap.sh terraform-eks
/opt/aws/bin/cfn-signal --exit-code $? \
	 --stack  terraform-eks \
	 --resource NodeGroup  \
	 --region us-west-2  \
     --kubelet-extra-args  \
     "--register-with-taints="environment=dev:NoSchedule"  \
     --node-labels=com.site/environment=dev"
DATA
}
```

**Comment by JessieAMorris** [comment]
This is what I'm using:

```  public-node-userdata = <<USERDATA
#!/bin/bash
set -o xtrace
/etc/eks/bootstrap.sh --apiserver-endpoint '${aws_eks_cluster.eks.endpoint}' --b64-cluster-ca '${aws_eks_cluster.eks.certificate_authority.0.data}' --kubelet-extra-args '--register-with-taints="ip=rotating:NoExecute" --node-labels="ip=rotating"' '${var.cluster_name}'
USERDATA
```

**Comment by christiangda** [comment]
As most of you mentioned, the problems are the quotes,  I'm using cfn template to deploy my nodes and after spent some time checking it, I created a custom userData script:

```yaml
        UserData:
          Fn::Base64: !Sub |
```
```bash
            #!/bin/bash
            set -e
            set -o xtrace

            CMD_EXTRA_ARG=""
            FIXED_NODES_LABELS="aws.eks.cluster=${ClusterName},aws.eks.nodegroup=${NodeGroupName}"
            FIXED_NODES_TAINTS=""

            # Add more arguments from parameter
            if [ ! -z "${AditionalExtraArguments}" ]
            then
              CMD_EXTRA_ARG=$CMD_EXTRA_ARG"${AditionalExtraArguments}"
            fi

            # Add more labels from parameter
            if [ ! -z "${CustomNodeLabels}" ]
            then
              if [ ! -z "$FIXED_NODES_LABELS" ]
              then
                NODES_LABELS=$FIXED_NODES_LABELS,${CustomNodeLabels}
              else
                NODES_LABELS=${CustomNodeLabels}
              fi
              CMD_EXTRA_ARG=$CMD_EXTRA_ARG" --node-labels="$NODES_LABELS
            fi

            # Add more taints from parameter
            if [ ! -z "${CustomNodeTaints}" ]
            then
              if [ ! -z "$FIXED_NODES_TAINTS" ]
              then
                NODES_TAINTS=$FIXED_NODES_TAINTS,${CustomNodeTaints}
              else
                NODES_TAINTS="\"${CustomNodeTaints}\""
              fi
              CMD_EXTRA_ARG="$CMD_EXTRA_ARG --register-with-taints=$NODES_TAINTS"
            fi

            if [ ! -z "$CMD_EXTRA_ARG" ]
            then
              /etc/eks/bootstrap.sh ${ClusterName} ${BootstrapArguments} --kubelet-extra-args "$CMD_EXTRA_ARG"
            else
              /etc/eks/bootstrap.sh ${ClusterName} ${BootstrapArguments}
            fi

            /opt/aws/bin/cfn-signal --exit-code $? \
                    --stack ${AWS::StackName} \
                    --resource NodeGroup  \
                    --region ${AWS::Region}

```

My cfn parameters template are

```yaml
  CustomNodeLabels:
    Type: String
    Default: ""
    Description: |
      String in format key1=value1,key2=value2,... see: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
      Example: custom.workload.type=monitoring,custom.company=SomeCompany

  CustomNodeTaints:
    Type: String
    Default: ""
    Description: |
      String in format key1=value1:NoSchedule,key2=value2:NoExecute,... see: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
      Example: dedicated=monitoring:NoSchedule

  BootstrapArguments:
    Type: String
    Default: ""
    Description: |
      Arguments to pass to the bootstrap script. Do not include '--kubelet-extra-args', see files/bootstrap.sh in https://github.com/awslabs/amazon-eks-ami
      see: https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh
      Example: --use-max-pods false --enable-docker-bridge true

  AditionalExtraArguments:
    Type: String
    Default: ""
    Description: |
      Aditional --kubelet-extra-args arguments, do not include labels or taints
      see: https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh
      Example: --system-reserved=memory=1Gi --kube-reserved=memory=256Mi
```

This is not the best way to solve it, but maybe work for you
