### ISSUE TITLE
InstanceIdNodeName causes bootstrapping to fail

### ISSUE THREAD

**Issue by universam1** [awslabs/amazon-eks-ami#1821]
**What happened**:

Enabling the feature gate InstanceIdNodeName according to https://awslabs.github.io/amazon-eks-ami/nodeadm/doc/examples/#using-instance-id-as-node-name-experimental causes the bootstrapping to fail.

**What you expected to happen**:

To get an error message in ec2 system logs or to succeed

**How to reproduce it (as minimally and precisely as possible)**:

Add to the NodeConfig
```
apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
  kubelet:
    config:
      featureGates:
        InstanceIdNodeName: true
```

**Anything else we need to know?**:

Tested both in Cloudwatch AutoscalingGroup and Karpenter nodes as well, same behaviour.

The Node IAM role is in place as described.

**Environment**:
- AWS Region: us-east-2
- Instance Type(s): t3, r6
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.28
- AMI Version: amazon-eks-node-al2023-x86_64-standard-1.28-v20240514
