### ISSUE TITLE
Node doesn't join EKS cluster when trying to setup LocalStorageOptions in User Data

### ISSUE THREAD

**Issue by ob-uk** [awslabs/amazon-eks-ami#2052]
**Environment**:
- AWS Region: us-west-2
- Instance Type(s): g5.xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.2
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.31
- AMI Version: AL2023_x86_64_NVIDIA

I'm trying to utilize the local instance store volumes on my g5.xlarge node. I modified the launch template to have the following UserData. However, after this when I try to bump the min size to 1 to bring up a new node, it does not join the cluster. I confirmed that the EC2 instance exists and is healthy, but does not join the cluster. 

What am I doing wrong and how can I enable using local storage volumes? 

```
Content-Type: multipart/mixed; boundary="MIMEBOUNDARY"
MIME-Version: 1.0

--MIMEBOUNDARY
Content-Transfer-Encoding: 7bit
Content-Type: application/node.eks.aws
Mime-Version: 1.0

---
apiVersion: node.eks.aws/v1alpha
kind: NodeConfig
spec:
  cluster:
    name: <clusterName>
    apiServerEndpoint: <apiServerEndpoint>
    certificateAuthority: <certificateAuthority>
    cidr: <cidr>
  instance:
    localStorage:
      strategy: RAID0

--MIMEBOUNDARY--
```

The information under `cluster` is correct, I've validated it against the `describe-cluster` output.
