### ISSUE TITLE
Nodeadm Documentation Clarification

### ISSUE THREAD

**Issue by antmatts** [awslabs/amazon-eks-ami#2139]
I wasn't able to submit my own change, but I have a request to update/clarify the current Nodeadm documentation, https://github.com/awslabs/amazon-eks-ami/tree/main/doc/nodeadm.

As `cidr` is now a required minimum parameter, can a quick note be added to clarify that `cidr` references the Kubernetes cluster CIDR and not the VPC CIDR? I've run into a few instances where this has been confused as needing to be set to the VPC CIDR, which causes issues with `kubelet`. Most notably, the default `/etc/resolv.conf` for pods isn't configured with the expected default of the `kube-dns` Service IP.

**Comment by zvickery** [comment]
Wow, was just about to file a similar ticket!  I am migrating from AL2 to AL2023 and noticed that DNS on the AL2023 pods is broken (it's fine on the nodes themselves).  Digging further, it's because `clusterDNS` in `kubelet/config.json` on AL2 is set to the `kube-dns` cluster IP.  On AL2023 it is set to the VPC CIDR (10.x/16) but with the last digit forced to 10.  This IP ends up in `resolv.conf` and is broken.

For AL2, there is some logic in `bootstrap.sh` that was forcing the cluster DNS setting for 10.x/16 to use the cluster IP:  https://github.com/awslabs/amazon-eks-ami/blob/cc55092f739650df3a1104bdb982dafe0ef12c63/templates/al2/runtime/bootstrap.sh#L476C93-L476C112

This logic is not replicated in `net.go` for AL2023:  https://github.com/awslabs/amazon-eks-ami/blob/cc55092f739650df3a1104bdb982dafe0ef12c63/nodeadm/internal/api/net.go#L17

I hadn't even considered that the CIDR setting for `nodeadm` was not a VPC CIDR.  How does one find the correct CIDR setting for the cluster to be passed into `nodeadm`?

**Comment by cartermckinnon** [comment]
You can get this with a DescribeCluster call (along with the endpoint and CA). I’ll get the docs updated 👍

**Comment by edify42** [comment]
I had a similar experience with @zvickery  - We've run EKS for almost 5 years now and most of that time with cilium as the CNI.

As part of the migration to amazonlinux2023, we migrated a smaller subset of our self-managed nodes to amazonlinux2023 and the pods come up healthy except the ones that make outbound network connections and rely on a working DNS to resolve hostnames.

Debugging on the pod led me to seeing differences between in the `/etc/resolv.conf` file that is set on the pod. For our cluster, we need the resolver to be `172.20.0.10` (which is the kube-dns service IP in the kube-system namespace) as shown below:

```text
root@datadog-latest-helm-datadog-cjv6q:/# cat /etc/resolv.conf 
search datadog.svc.cluster.local svc.cluster.local cluster.local
nameserver 172.20.0.10
options ndots:5
```

The fix for us to force this to happen on the amazonlinux2023 nodes is to update the `NodeConfig` section which is now used to bootstrap the nodes with the `clusterDNS` key below:

```yaml
apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
  cluster:
    name: ${CLUSTER_NAME}
    apiServerEndpoint: ${MASTER_ENDPOINT}
    certificateAuthority: ${CERT_AUTH_DATA_B64}
    cidr: ${VPC_CIDR}
  kubelet:
    config:
      maxPods: 40
      registryPullQPS: 20
      registryBurst: 40
      registerWithTaints:
        - effect: NoSchedule
          key: node.cilium.io/agent-not-ready
          value: "true"
        - effect: NoSchedule
          key: airflow-only
          value: "true"
      clusterDNS:
        - 172.20.0.10
```
