### ISSUE TITLE
Kubelet cluster-dns parameter is set incorrectly

### ISSUE THREAD

**Issue by drewhemm** [awslabs/amazon-eks-ami#222]
**What happened**: Potentially related to https://github.com/awslabs/amazon-eks-ami/issues/78 and https://github.com/awslabs/amazon-eks-ami/issues/197. 

`/etc/kubernetes/kubelet/kubelet-config.json` has the wrong value for clusterDNS, which is set by bootstrap.sh. This results in pods being unable to resolve DNS names. 

**What you expected to happen**: I would expect to see the correct nameserver in `/etc/kubernetes/kubelet/kubelet-config.json` and in `/etc/resolv.conf` on all pods running in the cluster.

**How to reproduce it (as minimally and precisely as possible)**: Create EKS service. My VPC happens to have two subnets (10.50.112.0/26 and 10.9.0.0/18, not sure that is relevant). Create worker instances. Most have the correct nameserver values in `/etc/kubernetes/kubelet/kubelet-config.json`, but not all. For the worker nodes that have the wrong value, pods  cannot resolve DNS queries. 

**Anything else we need to know?**:

**Environment**:
- AWS Region: eu-west-1
- Instance Type(s): c5.2xlarge, r5.2xlarge, other instance types too
- EKS Platform version: eks.2
- Kubernetes version: 1.11
- AMI Version: https://github.com/awslabs/amazon-eks-ami/commit/6090f200669ba1f76ce68f23e6496b3df9bc588a
- Kernel (e.g. `uname -a`): Linux 4.14.104-95.84.amzn2.x86_64
- Release information (run `cat /tmp/release` on a node):

```
cat: /tmp/release: No such file or directory
```

This issue still exists with the latest AMI code. An instance I created last week from an AMI built from the master branch (https://github.com/awslabs/amazon-eks-ami/commit/6090f200669ba1f76ce68f23e6496b3df9bc588a) has the wrong nameserver address in `/etc/kubernetes/kubelet/kubelet-config.json`:

```
...
"clusterDNS": [
  "10.100.0.10"
],
...
```
The instance is deployed into a VPC with two subnet CIDRs: 10.50.112.0/26 and 10.9.0.0/18.

It does not happen all the time. Other instances created around the same time and from the same AMI have the correct value. It is an intermittent bug that I have encountered on numerous occasions but am yet to find the exact cause.

**Comment by whereisaaron** [comment]
Ref #221

**Comment by micahhausler** [comment]
Can you provide a few more details about your VPC setup? 

* VPC CIDR
* Subnet CIDR ranges provided to EKS cluster
* Subnet CIDR ranges of nodes
* Any special networking setup

**Comment by drewhemm** [comment]
* VPC CIDRs: 10.50.112.0/24 & 10.9.0.0/16
* 'overlay' subnets: 10.50.112.0/26, 10.50.112.64/26, 10.50.112.64/26, 'underlay' subnets: 10.9.0.0/18, 10.9.64.0/18 & 10.9.128.0/18
* As above
* Special networking setup...

I am using [CNI custom networking](https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html) because we have a limited number of IP addresses in the 10.50.112.0/24 CIDR as that subnet is mapped into our corporate IP space. The 10.50.112.x/26 CIDRS are used by the nodes and the 10.9.0.x/18 IPs are used by the pods. 

In the instance metadata, I am attaching a secondary network interface as follows:

```
#!/bin/bash
set -o xtrace
# Secondary ENI for the underlay, code lifted from
# https://stackoverflow.com/questions/19836854/aws-cloudformation-networkinterfaces-in-autoscaling-launchconfig-group
export AWS_DEFAULT_REGION=eu-west-1

# Get the instance ID
INSTANCE_ID=$(curl -sS http://169.254.169.254/latest/meta-data/instance-id)

# And the AZ
AZ=$(curl -sS http://169.254.169.254/latest/meta-data/placement/availability-zone)

# Find the matching underlay subnet for this AZ
SUBNET_ID=$(aws ec2 describe-subnets --subnet-ids {{ underlay_subnets | join(" ")}} --filters Name=availabilityZone,Values=$AZ --query 'Subnets[0].SubnetId' --output text)

# Create a new network interface
ENI_ID=$(aws ec2 create-network-interface --subnet $SUBNET_ID --description 'Secondary ENI' --groups ${UnderlaySecurityGroup} --query 'NetworkInterface.NetworkInterfaceId' --output text)

# and tag it...
aws ec2 create-tags --resources $ENI_ID --tags 'Key=Foo,Value=Bar'

# Disable source dest check
# aws ec2 modify-network-interface-attribute --network-interface-id $ENI_ID --no-source-dest-check --output text

# Attach the interface to the instance
ATTACHMENT_ID=$(aws ec2 attach-network-interface --network-interface-id $ENI_ID --instance-id $INSTANCE_ID --device-index 1 --output text)

# Set the interface to delete upon instance termination
aws ec2 modify-network-interface-attribute --network-interface-id $ENI_ID --attachment AttachmentId=$ATTACHMENT_ID,DeleteOnTermination=true --output text
```
I am using Ansible and Jinja2 templating to generate the CloudFormation template, hence why there are some `{{ variables }}` in the code.

**Comment by drewhemm** [comment]
In the event that a call to the metadata service fails (I recall now that I faced this problem before on an unrelated AWS project a few years back), what would be the ideal thing to do? Exit the script with `exit 1` or retry the call up to x times with exponential backoff and `exit 1` if it reaches x retries and still fails?

**Comment by drewhemm** [comment]
I've found a process that iterates through EC2 instances using k8s:

* Create a worker node group with 100 instances, apply a custom node role/label
* Create a deployment that targets the aforementioned role/label, set to 100 replicas:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterdns-test
  namespace: default
spec:
  replicas: 100
  selector:
    matchLabels:
      app: clusterdns-test
  template:
    metadata:
      labels:
        app: clusterdns-test
    spec:
      nodeSelector:
        kubernetes.io/role: test
      containers:
        - name: test
          command:
            - sleep
            - "3600"
          image: busybox
          readinessProbe:
            exec:
              command:
                - grep
                - "172.20.0.10"
                - /etc/resolv.conf
            failureThreshold: 1
            initialDelaySeconds: 10
            timeoutSeconds: 2
          resources:
            requests:
              cpu: "1500m" # used to ensure no more than one pod gets scheduled onto a t3.small instance, faster scheduling than using podAntiAffinity
      tolerations:
        - operator: Exists
```
The readinessProbe is used to identify pods on nodes with the incorrect `clusterDNS` value. So far, I have been able to observe one faulty instance in over 600 EC2 instances. My real-world observation rate was much higher. 

It's possible this would be quicker if I were to do some checking on the node using a script in the userdata rather than relying on k8s; will look into that tomorrow...
