### ISSUE TITLE
Support for post-nodeadm user data

### ISSUE THREAD

**Issue by phuhung273** [awslabs/amazon-eks-ami#2224]
**What would you like to be added**:
nodeadm support a field called `post_user_data_path` pointing to a script that need to be executed after `nodeadm-run` finish

```
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="//"

--//
Content-Type: application/node.eks.aws

apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
  instance:
    post_user_data_path: /home/ec2/post-nodeadm-run.sh

--//
Content-Type: text/x-shellscript; charset="us-ascii"

#!/bin/bash
echo "pull_common_images()" > /home/ec2/post-nodeadm-run.sh
--//
```

**Why is this needed**:
On AL2, after node join cluster (top priority), we pull some commonly used images to optimize performance, user data is like:
```
bootstrap.sh <cluster_name>

ctr images pull my-common-images:latest
```

On AL2023, the only place to specify bash script is in `multipart/mixed` user data (correct me if im wrong please). But nodeadm-run (cluster joining) is blocked until this bash finish. So we end up sacrifying cluster joining performance or cannot pull common images.

**Current Workaround**
Bake a systemd service running after nodeadm-run
