### ISSUE TITLE
bug(AL2023/cilium@1.15): Pods Cannot Connect to Internet

### ISSUE THREAD

**Issue by ariretiarno** [awslabs/amazon-eks-ami#2251]
**What happened**:
I currently want to upgrade from Amazon Linux 2 to Amazon Linux 2023 because Amazon Linux 2 will deprecated at the end of the year.
I'm using karpenter to handling autoscaling cluster.

When I'm use Public Subnet (via Internet Gateway) the pods is not connected to outside and cannot communicate within the cluster. I also use SSM to directly connect to nodes and the try to ping to outside it's works. 

But when i'm using private subnet with nat gateways seems normal, the pods can connect to outside cluster

**What you expected to happen**:
Can Connect to internet when using public subnet.

**How to reproduce it (as minimally and precisely as possible)**:

<img width="1211" alt="Image" src="https://github.com/user-attachments/assets/b7904846-aa02-4ea0-816f-eb6970fb7902" />

**Environment**:
- AWS Region: ap-southeast-1
- Instance Type(s): t3.large
- Cluster Kubernetes version: v1.30.11-eks-bcf3d70
- Node Kubernetes version: v1.30.11-eks-473151a
- AMI Version: Amazon Linux 2023.7.20250428
- Cilium v1.15

**Comment by mselim00** [comment]
Hi @ariretiarno , can you open an AWS Support Case for this issue? I'm not able to reproduce this so it would be helpful to get collect more details through that

**Comment by mselim00** [comment]
I opened https://github.com/cilium/cilium/issues/39684 for this, I haven't been able to identify the issue. I did see that the latest release on the 1.15 branch still manifests this issue

**Comment by mselim00** [comment]
This seems to not be a bug, 1.30 is not in the official support matrix for 1.15 https://docs.cilium.io/en/v1.15/network/kubernetes/compatibility/

Cilium lists 1.30 as [a supported version on 1.16](https://docs.cilium.io/en/v1.16/network/kubernetes/compatibility/) and [a tested version on 1.17](https://raw.githubusercontent.com/cilium/cilium/v1.17/.github/actions/eks/k8s-versions.yaml)

**Comment by ariretiarno** [comment]
ahh thankyou @mselim00 , i'll try to update the cilium too..

**Comment by jarvrans** [comment]
@ariretiarno did updating Cilium resolve the issue?

**Comment by ariretiarno** [comment]
> [@ariretiarno](https://github.com/ariretiarno) did updating Cilium resolve the issue?

I've been upgrade to v1.17.7 but didn't works.
Seems my pod cannot connect to internet gateway.

here is my helm release value
```
    routingMode: "native"
    upgradeCompatibility: "1.16"
    imagePullSecrets:
    - name: "evermos-docker"  
    eni:
      enabled: true
    ipam:
      mode: eni
    egressMasqueradeInterfaces: eth0
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            # This is to limit cilium only running on the nodes
            # WITHOUT label cni-plugin=aws
            - key: cni-plugin
              operator: NotIn
              values:
              - aws
    hubble:
      enabled: true
      relay:
        enabled: true
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: evermos.com/serviceClass
                    operator: In
                    values:
                    - internal-tier-one
        tolerations:
          - effect: NoSchedule
            key: internal-tier-one
            operator: Equal
            value: "true"
      ui:
        enabled: true
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: evermos.com/serviceClass
                    operator: In
                    values:
                    - internal-tier-one
        tolerations:
          - effect: NoSchedule
            key: internal-tier-one
            operator: Equal
            value: "true"
    prometheus:
      enabled: true
    operator:
      prometheus:
        enabled: true
      extraArgs: 
        - --aws-enable-prefix-delegation
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: evermos.com/serviceClass
                  operator: In
                  values:
                  - internal-tier-one
      tolerations:
        - effect: NoSchedule
          key: internal-tier-one
          operator: Equal
          value: "true" 
    nodeinit:
      enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
```

cc @mselim00
