### ISSUE TITLE
feat(nodeadm): Add certificate authority installation to NodeConfig

### ISSUE THREAD

**Issue by JoeNorth** [awslabs/amazon-eks-ami#2296]
**What would you like to be added**:
A new `pki` section to the `NodeConfigSpec` which allows for users to specify inline files, http links, or s3 URIs to download the certificate bundle remotely and add to the node's trust store.

Example:

```
apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
  cluster:
    name: my-cluster
    apiServerEndpoint: https://example.com
    certificateAuthority: Y2VydGlmaWNhdGVBdXRob3JpdHk=
    cidr: 10.100.0.0/16
  pki:
    - name: private-ca-1
      data: |
        -----BEGIN CERTIFICATE-----
        MIIH/TCCBeWgAwIBAgIQaBYE3/M08XHYCnNVmcFBcjANBgkqhkiG9w0BAQsFADBy
        ...
        -----END CERTIFICATE-----
    - name: private-ca-2
      path: https://example.com/private-ca-2.pem
    - name: private-ca-3
      path: s3://example-com/private-ca-3.pem
```

**Why is this needed**:
A common pre-bootstrapping action is adding private certificate authorities into the node's trust store for communication with internal container registries and other endpoints. At this time, this must be done in userdata by adding a separate `text/x-shellscript` section or maintaining a custom AMI where this certificate has already been added.

Following Bottlerocket's lead and adding this as an action that can be done during bootstrapping would go a long way toward removing custom bootstrapping scripts and custom AMI maintenance.

**Comment by cartermckinnon** [comment]
I'm not sure this in scope for `nodeadm`, unless the CA certs are needed for `nodeadm`'s own operation. If you don't want to install them with an `text/x-shellscript`, you could use `text/cloud-config`: https://cloudinit.readthedocs.io/en/latest/reference/modules.html#mod-cc-ca-certs

> Following Bottlerocket's lead and adding this as an action that can be done during bootstrapping

There's a fundamental difference here: Bottlerocket *only* has a declarative settings API. Our Amazon Linux AMIs have `NodeConfig` (inspired by the Bottlerocket approach) in addition to `cloud-init`. The goal of `NodeConfig` isn't exactly the same as Bottlerocket's settings API; it's not intended to configure anything/everything about the OS. Much of that is already solved by `cloud-init`.

We aim to keep `NodeConfig` scoped to Kubernetes-related parts of the system, but we take this case-by-case -- if we can offer something simpler or more ergonomic, great! In this case, I don't think the `NodeConfig` approach would really be any simpler than the other existing options:
```
# NodeConfig
spec:
  pki:
    - name: private-ca-1
      data: |
        -----BEGIN CERTIFICATE-----
        ...
```
versus:
```
# cloud-config
ca_certs:
  trusted:
  - single_line_cert
  - |
    -----BEGIN CERTIFICATE-----
    ...
```
versus:
```
# x-shellscript

aws s3 cp s3://bucket/cert.pem > /etc/pki/...
curl https://example.com/cert.pem > /etc/pki/...
```
