### ISSUE TITLE
The 2nd stack in EKS cluster has DNS problem

### ISSUE THREAD

**Issue by left4taco** [awslabs/amazon-eks-ami#382]
**What happened**:

We were using the CloudFormation template to create the stack, which contains several ASGs as work node in the EKS cluster. However when we tried to add a second stack using the same template, PODs in the second stack cannot resolve any domain, but can ping 8.8.8.8. 

Here's a minimal reproducible example. https://github.com/left4taco/AWS_EKS_MRE

It's very easy to follow. We've also add unique name to all the resources created by the template so that the second cluster has no conflicts with the first one. Could someone from AWS give it a look? I believe this might lead to discovery of a bug. 

**Environment**:
- AWS Region: us-west-2
- Instance Type(s): c5.18xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks2 ~ eks5
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.14
- AMI Version: Most recent(20191126?)

```
```

**Comment by rimaulana** [comment]
@left4taco The issue you are experiencing was because node from different ASG (second stack) doesn't share the same security group. One of the important rule is this one

```yaml
  NodeSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    DependsOn: NodeSecurityGroup
    Properties:
      Description: Allow node to communicate with each other
      GroupId: !Ref NodeSecurityGroup
      SourceSecurityGroupId: !Ref NodeSecurityGroup
      IpProtocol: '-1'
      FromPort: 0
      ToPort: 65535
```

This will allow pods running on nodes that uses NodeSecurityGroup to be able to communicate with each other. In your case, node from ASG 1 has its own NodeSecurityGroup while node from ASG 2 has different NodeSecurityGroup. In your case, CoreDNS pod runs on node from ASG 1 and will only be reachable from any pods running on a node from ASG 1.

If your use case is to work with multiple ASG, then I would recommend to create Node security group to be created outside of the stack, could be manual or via separate stack. Then the security group id can be pass as a parameter for the node stack or imported into the node stack. By doing this, all nodes from different ASG will have the same security group
