### ISSUE TITLE
IPVS support?

### ISSUE THREAD

**Issue by tschirmer** [awslabs/amazon-eks-ami#546]
**What would you like to be added**:

Kernal IPVS Install within the AMI as a default.

For production clusters with a large amount of services, iptables causes a range of issues including load balancing.

I'll refer to Jeremy Cowan's article:
https://medium.com/@jeremy.i.cowan/the-problem-with-kube-proxy-enabling-ipvs-on-eks-169ac22e237e

**Why is this needed**:

This strictly could be done via eksctl, but due to the global nature of the problem and the ease of implementation, I really think this kube-proxy mode should be available in the ami as a default. Once that's available, it'd be a matter of configuring calico + kube-proxy to use it or not use it.

**Comment by tschirmer** [comment]
Bumping this. Anyone looking into this 1 year on?

**Comment by mars64** [comment]
Just chiming in with my recent observations. I recently upgraded all my clusters to latest as of this writing:

```
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

I also just moved `kube-proxy` to be managed by the eks addons thingy in the ui. We weren't previously explicitly managing this config, and I didn't check it before the upgrade so i'm not sure if this is new or old. But ...

* `kube-proxy` configmap seems to have a stub config for ipvs now:

```
% kubectl -n kube-system get cm kube-proxy-config -o yaml
apiVersion: v1
data:
  config: |-
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    bindAddress: 0.0.0.0
    clientConnection:
      acceptContentTypes: ""
      burst: 10
      contentType: application/vnd.kubernetes.protobuf
      kubeconfig: /var/lib/kube-proxy/kubeconfig
      qps: 5
    clusterCIDR: ""
    configSyncPeriod: 15m0s
    conntrack:
      maxPerCore: 32768
      min: 131072
      tcpCloseWaitTimeout: 1h0m0s
      tcpEstablishedTimeout: 24h0m0s
    enableProfiling: false
    healthzBindAddress: 0.0.0.0:10256
    hostnameOverride: ""
    iptables:
      masqueradeAll: false
      masqueradeBit: 14
      minSyncPeriod: 0s
      syncPeriod: 30s
    ipvs:
      excludeCIDRs: null
      minSyncPeriod: 0s
      scheduler: ""
      syncPeriod: 30s
    kind: KubeProxyConfiguration
    metricsBindAddress: 127.0.0.1:10249
    mode: "iptables"
    nodePortAddresses: null
    oomScoreAdj: -998
    portRange: ""
    udpIdleTimeout: 250ms
kind: ConfigMap
```

* Then I verified that the nodes (`v1.21.5-eks-bc4871b`) indeed seem to have the correct modules loaded:

```
# lsmod | grep ip_vs
ip_vs_sh               16384  0
ip_vs_wrr              16384  0
ip_vs_rr               16384  0
ip_vs                 176128  6 ip_vs_rr,ip_vs_sh,ip_vs_wrr
nf_conntrack          163840  8 xt_conntrack,nf_nat,xt_state,xt_nat,nf_conntrack_netlink,xt_connmark,xt_MASQUERADE,ip_vs
nf_defrag_ipv6         24576  2 nf_conntrack,ip_vs
```

I haven't yet tested this (and may end up not going this way for my case tbh), but it _appears_ that all that needs to be done is changing the configmap from `mode: "iptables"` to `mode: "ipvs"` and restart `kube-proxy`.

Sidenotes: 

* it seems like maybe this issue is a dupe of https://github.com/aws/containers-roadmap/issues/142 (or maybe that issue should be moved here?)
* I used https://jicowan.medium.com/the-problem-with-kube-proxy-enabling-ipvs-on-eks-169ac22e237e to understand how others were implement ipvs
