### ISSUE TITLE
CronJobs failing to start: Getting the final child's pid from pipe caused "EOF"

### ISSUE THREAD

**Issue by mmerkes** [awslabs/amazon-eks-ami#592]
**What happened**:
CronJob produces seemingly random warnings relating to sandbox creation issues.

```
Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "hello-1603208700-v642l": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:319: getting the final child's pid from pipe caused \"EOF\"": unknown
```

**What you expected to happen**:

CronJob to successfully deploy and complete.

**How to reproduce it (as minimally and precisely as possible)**:

Follow the generic Cron Job creation listed on the OSS Kubernetes site.

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

```
kubectl create -f https://k8s.io/examples/application/job/cronjob.yaml
```

Eventually, OCI error will appear.

**Anything else we need to know?**:

This appears to be [a known Docker issue](https://github.com/moby/moby/issues/40835), and a customer opened up a ticket to [Kubernetes](https://github.com/kubernetes/kubernetes/issues/95916), but creating here since it appears to be a Docker issue and it's possible that the issue can be mitigated directly in this AMI. For example, increasing PIDs as described [here](https://github.com/moby/moby/issues/40835#issuecomment-730981130).

**Environment**:
- AWS Region:
- Instance Type(s):
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version:
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```
