### ISSUE TITLE
CoreDNS is broken on managed nodes launched with Taints

### ISSUE THREAD

**Issue by npapapietro** [awslabs/amazon-eks-ami#681]
**What happened**:

Launching a new EKS cluster via terraform with `--register-with-taints` on one managed node group and nothing on a 2nd managed node group causes the tainted managed node group to break all networking.

**What you expected to happen**:

Tainted node should have networking

**How to reproduce it (as minimally and precisely as possible)**:

Using terraform ([module](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/v17.1.0)) create an EKS cluster with a managed node group as such: 
```hcl
system-services = {
      create_launch_template = true
      kubelet_extra_args     = "--register-with-taints=system-services=true:NoSchedule"
     // other args
}
```
Launch a pod 
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
spec:
  tolerations: # add/remove this to allow for dnsutils on each node
    - key: "system-services"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
```

try to `nslookup` a pod on the tainted node and it times out, try the same on untainted node and it works as expected

**Anything else we need to know?**:

Seems to be a new case of: https://github.com/awslabs/amazon-eks-ami/issues/200

**Environment**:
- AWS Region: `us-east-2`
- Instance Type(s): `m4.large`
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): `eks.1`
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): `1.20`
- AMI Version: `ami-004a571bc4ab7023a`
- Kernel (e.g. `uname -a`): `5.4.117-58.216.amzn2.x86_64`
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-004a571bc4ab7023a"
BUILD_TIME="Wed May 26 18:04:12 UTC 2021"
BUILD_KERNEL="5.4
```
