### ISSUE TITLE
Provide a container native way to collect logs

### ISSUE THREAD

**Issue by mtparet** [awslabs/amazon-eks-ami#833]
**What would you like to be added**:

Be able to collect only using kubernetes commands.

**Why is this needed**:

SSM or SSH access should not be require to run eks logs script.

Currently I manage it by running a pod mount host root but we should have an official way.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-logs
  labels:
    app: eks-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-logs
  template:
    metadata:
      labels:
        app: eks-logs
    spec:
      containers:
      - name: eks-logs
        image: ubuntu:21.04
        command: ["sleep"]
        args: ["1800"]
        volumeMounts:
        - mountPath: /host-root
          name: host-root
        securityContext:
          privileged: true
      volumes:
      - name: host-root
        hostPath:
          # directory location on host
          path: /
          # this field is optional
          type: Directory
      nodeSelector:
        kubernetes.io/hostname: XXXX
```
